import type {
  Run,
  Agent,
  Task,
  RunEvent,
  DecisionGate,
  Outcome,
} from "@/types/entities";

// ─── Mock Run ───

export const mockRun: Run = {
  id: "run-bakery-001",
  scenario_id: "scn-bakery-001",
  status: "executing",
  mode: "explore",
  agent_roster: [
    { id: "agent-architect", name: "Blueprint", role: "architect" },
    { id: "agent-analyst", name: "Lens", role: "analyst" },
    { id: "agent-operator", name: "Gears", role: "operator" },
    { id: "agent-guardian", name: "Shield", role: "guardian" },
    { id: "agent-narrator", name: "Chronicle", role: "narrator" },
  ],
  task_graph: [
    { from_task_id: "task-001", to_task_id: "task-002", relation: "depends_on" },
    { from_task_id: "task-001", to_task_id: "task-003", relation: "depends_on" },
    { from_task_id: "task-002", to_task_id: "task-004", relation: "depends_on" },
    { from_task_id: "task-003", to_task_id: "task-004", relation: "depends_on" },
    { from_task_id: "task-004", to_task_id: "task-005", relation: "depends_on" },
    { from_task_id: "task-004", to_task_id: "task-006", relation: "depends_on" },
    { from_task_id: "task-005", to_task_id: "task-007", relation: "depends_on" },
    { from_task_id: "task-006", to_task_id: "task-007", relation: "depends_on" },
    { from_task_id: "task-007", to_task_id: "task-008", relation: "depends_on" },
  ],
  summary: "Launching a pop-up bakery in 10 days with a borrowed kitchen.",
  started_at: "2026-04-09T14:00:00Z",
  ended_at: null,
  progress: 42,
};

// ─── Mock Agents ───

export const mockAgents: Agent[] = [
  {
    id: "agent-architect",
    run_id: "run-bakery-001",
    name: "Blueprint",
    role: "architect",
    capabilities: ["decomposition", "dependency_mapping", "phase_planning"],
    confidence: 0.87,
    state: "thinking",
    current_task_id: "task-004",
    last_action: "Mapped supply chain dependencies",
    messages_sent: 12,
    messages_received: 8,
  },
  {
    id: "agent-analyst",
    run_id: "run-bakery-001",
    name: "Lens",
    role: "analyst",
    capabilities: ["risk_assessment", "cost_estimation", "data_analysis"],
    confidence: 0.73,
    state: "acting",
    current_task_id: "task-005",
    last_action: "Identified 3 budget overrun risks",
    messages_sent: 9,
    messages_received: 11,
  },
  {
    id: "agent-operator",
    run_id: "run-bakery-001",
    name: "Gears",
    role: "operator",
    capabilities: ["scheduling", "resource_allocation", "vendor_coordination"],
    confidence: 0.91,
    state: "acting",
    current_task_id: "task-003",
    last_action: "Secured borrowed kitchen for days 3-10",
    messages_sent: 15,
    messages_received: 7,
  },
  {
    id: "agent-guardian",
    run_id: "run-bakery-001",
    name: "Shield",
    role: "guardian",
    capabilities: ["compliance_check", "safety_review", "risk_monitoring"],
    confidence: 0.65,
    state: "waiting",
    current_task_id: null,
    last_action: "Flagged food safety permit gap",
    messages_sent: 6,
    messages_received: 14,
  },
  {
    id: "agent-narrator",
    run_id: "run-bakery-001",
    name: "Chronicle",
    role: "narrator",
    capabilities: ["summarization", "progress_tracking", "stakeholder_comms"],
    confidence: 0.95,
    state: "idle",
    current_task_id: null,
    last_action: "Published progress update: Phase 1 complete",
    messages_sent: 4,
    messages_received: 18,
  },
];

// ─── Mock Tasks ───

export const mockTasks: Task[] = [
  {
    id: "task-001",
    run_id: "run-bakery-001",
    title: "Scenario decomposition",
    description: "Break the pop-up bakery challenge into structured phases with clear dependencies.",
    status: "completed",
    owner_agent_id: "agent-architect",
    depends_on: [],
    risk_level: "low",
    phase: "Planning",
    confidence: 0.95,
    started_at: "2026-04-09T14:00:30Z",
    completed_at: "2026-04-09T14:02:15Z",
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "task-002",
    run_id: "run-bakery-001",
    title: "Budget & cost analysis",
    description: "Estimate costs for ingredients, equipment rental, permits, and marketing within the limited budget.",
    status: "completed",
    owner_agent_id: "agent-analyst",
    depends_on: ["task-001"],
    risk_level: "medium",
    phase: "Planning",
    confidence: 0.82,
    started_at: "2026-04-09T14:02:20Z",
    completed_at: "2026-04-09T14:04:45Z",
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "task-003",
    run_id: "run-bakery-001",
    title: "Secure borrowed kitchen",
    description: "Negotiate kitchen access, verify equipment availability, and confirm scheduling for days 3-10.",
    status: "active",
    owner_agent_id: "agent-operator",
    depends_on: ["task-001"],
    risk_level: "high",
    phase: "Execution",
    confidence: 0.71,
    started_at: "2026-04-09T14:02:30Z",
    completed_at: null,
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "task-004",
    run_id: "run-bakery-001",
    title: "Permits & compliance review",
    description: "Identify all required food handling permits, health inspections, and temporary business licenses.",
    status: "blocked",
    owner_agent_id: "agent-guardian",
    depends_on: ["task-002", "task-003"],
    risk_level: "critical",
    phase: "Execution",
    confidence: 0.45,
    started_at: "2026-04-09T14:05:00Z",
    completed_at: null,
    retry_count: 1,
    failure_reason: "Waiting for kitchen confirmation to determine jurisdiction",
  },
  {
    id: "task-005",
    run_id: "run-bakery-001",
    title: "Supply chain sourcing",
    description: "Source ingredients from local suppliers with 48-hour delivery windows. Identify backup vendors.",
    status: "active",
    owner_agent_id: "agent-analyst",
    depends_on: ["task-002"],
    risk_level: "medium",
    phase: "Execution",
    confidence: 0.68,
    started_at: "2026-04-09T14:05:10Z",
    completed_at: null,
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "task-006",
    run_id: "run-bakery-001",
    title: "Marketing & neighborhood outreach",
    description: "Design flyers, set up social media, coordinate with local community board for pop-up announcement.",
    status: "awaiting_approval",
    owner_agent_id: "agent-operator",
    depends_on: ["task-004"],
    risk_level: "low",
    phase: "Execution",
    confidence: 0.88,
    started_at: null,
    completed_at: null,
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "task-007",
    run_id: "run-bakery-001",
    title: "Dry run & staff training",
    description: "Conduct a full practice run: bake test batches, rehearse service flow, verify POS system.",
    status: "queued",
    owner_agent_id: null,
    depends_on: ["task-005", "task-006"],
    risk_level: "medium",
    phase: "Preparation",
    confidence: 0.5,
    started_at: null,
    completed_at: null,
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "task-008",
    run_id: "run-bakery-001",
    title: "Grand opening execution",
    description: "Open doors, manage customer flow, handle real-time issues, collect feedback.",
    status: "queued",
    owner_agent_id: null,
    depends_on: ["task-007"],
    risk_level: "high",
    phase: "Launch",
    confidence: 0.35,
    started_at: null,
    completed_at: null,
    retry_count: 0,
    failure_reason: null,
  },
];

// ─── Mock Events ───

export const mockEvents: RunEvent[] = [
  {
    id: "evt-001",
    run_id: "run-bakery-001",
    type: "run_started",
    actor: "system",
    payload: { mode: "explore", scenario: "Pop-Up Bakery Sprint" },
    timestamp: "2026-04-09T14:00:00Z",
    sequence: 1,
  },
  {
    id: "evt-002",
    run_id: "run-bakery-001",
    type: "scenario_compiled",
    actor: "system",
    payload: { domain: "operations", safety_status: "safe", agents_count: 5 },
    timestamp: "2026-04-09T14:00:15Z",
    sequence: 2,
  },
  {
    id: "evt-003",
    run_id: "run-bakery-001",
    type: "agent_spawned",
    actor: "Blueprint",
    payload: { role: "architect", capabilities: ["decomposition", "dependency_mapping"] },
    timestamp: "2026-04-09T14:00:18Z",
    sequence: 3,
  },
  {
    id: "evt-004",
    run_id: "run-bakery-001",
    type: "agent_spawned",
    actor: "Lens",
    payload: { role: "analyst", capabilities: ["risk_assessment", "cost_estimation"] },
    timestamp: "2026-04-09T14:00:19Z",
    sequence: 4,
  },
  {
    id: "evt-005",
    run_id: "run-bakery-001",
    type: "agent_spawned",
    actor: "Gears",
    payload: { role: "operator", capabilities: ["scheduling", "resource_allocation"] },
    timestamp: "2026-04-09T14:00:20Z",
    sequence: 5,
  },
  {
    id: "evt-006",
    run_id: "run-bakery-001",
    type: "agent_spawned",
    actor: "Shield",
    payload: { role: "guardian", capabilities: ["compliance_check", "safety_review"] },
    timestamp: "2026-04-09T14:00:21Z",
    sequence: 6,
  },
  {
    id: "evt-007",
    run_id: "run-bakery-001",
    type: "agent_spawned",
    actor: "Chronicle",
    payload: { role: "narrator", capabilities: ["summarization", "progress_tracking"] },
    timestamp: "2026-04-09T14:00:22Z",
    sequence: 7,
  },
  {
    id: "evt-008",
    run_id: "run-bakery-001",
    type: "task_created",
    actor: "Blueprint",
    payload: { task_id: "task-001", title: "Scenario decomposition" },
    timestamp: "2026-04-09T14:00:30Z",
    sequence: 8,
  },
  {
    id: "evt-009",
    run_id: "run-bakery-001",
    type: "agent_thinking",
    actor: "Blueprint",
    payload: { thought: "Identifying key phases: planning, sourcing, preparation, launch" },
    timestamp: "2026-04-09T14:00:45Z",
    sequence: 9,
  },
  {
    id: "evt-010",
    run_id: "run-bakery-001",
    type: "task_status_changed",
    actor: "Blueprint",
    payload: { task_id: "task-001", from: "active", to: "completed" },
    timestamp: "2026-04-09T14:02:15Z",
    sequence: 10,
  },
  {
    id: "evt-011",
    run_id: "run-bakery-001",
    type: "task_assigned",
    actor: "system",
    payload: { task_id: "task-002", agent: "Lens", role: "analyst" },
    timestamp: "2026-04-09T14:02:20Z",
    sequence: 11,
  },
  {
    id: "evt-012",
    run_id: "run-bakery-001",
    type: "agent_action",
    actor: "Gears",
    payload: { action: "Secured borrowed kitchen for days 3-10", task_id: "task-003" },
    timestamp: "2026-04-09T14:03:00Z",
    sequence: 12,
  },
  {
    id: "evt-013",
    run_id: "run-bakery-001",
    type: "risk_identified",
    actor: "Shield",
    payload: {
      risk: "Food safety permit gap identified",
      severity: "critical",
      task_id: "task-004",
    },
    timestamp: "2026-04-09T14:04:00Z",
    sequence: 13,
  },
  {
    id: "evt-014",
    run_id: "run-bakery-001",
    type: "decision_gate_created",
    actor: "Shield",
    payload: {
      gate_id: "gate-001",
      reason: "Critical compliance gap: food handling permit not secured",
      risk_level: "critical",
    },
    timestamp: "2026-04-09T14:04:30Z",
    sequence: 14,
  },
  {
    id: "evt-015",
    run_id: "run-bakery-001",
    type: "retry_triggered",
    actor: "system",
    payload: { task_id: "task-004", attempt: 2, reason: "Jurisdiction dependency unresolved" },
    timestamp: "2026-04-09T14:05:00Z",
    sequence: 15,
  },
  {
    id: "evt-016",
    run_id: "run-bakery-001",
    type: "agent_message",
    actor: "Lens",
    payload: {
      to: "Blueprint",
      message: "Budget analysis complete. Total estimated cost: $2,840. Three risk areas flagged.",
    },
    timestamp: "2026-04-09T14:04:45Z",
    sequence: 16,
  },
  {
    id: "evt-017",
    run_id: "run-bakery-001",
    type: "escalation",
    actor: "Shield",
    payload: {
      task_id: "task-004",
      reason: "Permit timeline may exceed 10-day window",
      severity: "high",
    },
    timestamp: "2026-04-09T14:05:30Z",
    sequence: 17,
  },
  {
    id: "evt-018",
    run_id: "run-bakery-001",
    type: "narrator_update",
    actor: "Chronicle",
    payload: {
      summary:
        "Phase 1 planning complete. Phase 2 execution underway with one critical blocker: food safety permits. The team is exploring an expedited permit process while proceeding with parallel tasks.",
    },
    timestamp: "2026-04-09T14:06:00Z",
    sequence: 18,
  },
  {
    id: "evt-019",
    run_id: "run-bakery-001",
    type: "human_review_requested",
    actor: "Shield",
    payload: {
      gate_id: "gate-002",
      reason: "Marketing materials need human approval before neighborhood distribution",
      task_id: "task-006",
    },
    timestamp: "2026-04-09T14:06:30Z",
    sequence: 19,
  },
  {
    id: "evt-020",
    run_id: "run-bakery-001",
    type: "agent_thinking",
    actor: "Blueprint",
    payload: { thought: "Re-evaluating timeline: permit blocker may require phase reordering" },
    timestamp: "2026-04-09T14:07:00Z",
    sequence: 20,
  },
];

// ─── Mock Decision Gates ───

export const mockDecisionGates: DecisionGate[] = [
  {
    id: "gate-001",
    run_id: "run-bakery-001",
    task_id: "task-004",
    reason: "Critical compliance gap: food handling permit not secured within the 10-day window.",
    required_action: "Decide whether to proceed with expedited permit or pivot to a different venue type.",
    status: "pending",
    risk_level: "critical",
    options: [
      {
        label: "Expedite permit",
        description: "Pay rush processing fee ($350) for 3-day turnaround",
        action: "approve",
        consequence: "Adds $350 to budget but keeps original timeline intact",
      },
      {
        label: "Pivot to farmers market",
        description: "Switch venue to farmers market stall (no kitchen permit needed)",
        action: "reroute",
        consequence: "Reduces menu options but eliminates permit blocker entirely",
      },
      {
        label: "Delay launch",
        description: "Push opening to day 14 to allow standard permit processing",
        action: "reject",
        consequence: "Safer but breaks the 10-day constraint",
      },
    ],
    resolved_at: null,
    resolved_by: null,
  },
  {
    id: "gate-002",
    run_id: "run-bakery-001",
    task_id: "task-006",
    reason: "Marketing flyer content requires human review before neighborhood distribution.",
    required_action: "Review and approve marketing materials.",
    status: "approved",
    risk_level: "low",
    options: [
      {
        label: "Approve as-is",
        description: "Flyer looks good, proceed with printing",
        action: "approve",
        consequence: "Distribution begins immediately",
      },
      {
        label: "Request revisions",
        description: "Minor edits needed before printing",
        action: "reject",
        consequence: "Delays distribution by 4 hours",
      },
    ],
    resolved_at: "2026-04-09T14:08:00Z",
    resolved_by: "human",
  },
];

// ─── Mock Outcome ───

export const mockOutcome: Outcome = {
  id: "outcome-bakery-001",
  run_id: "run-bakery-001",
  executive_summary:
    "The pop-up bakery can launch within 10 days by securing an expedited food handling permit, leveraging a borrowed commercial kitchen, and executing a lean marketing strategy. Total projected cost: $2,840. Key risk: permit processing timeline. Mitigation: parallel farmers market fallback.",
  operating_plan: [
    {
      phase: "Phase 1",
      title: "Planning & Permits",
      description: "Secure all permits, finalize budget, confirm kitchen access.",
      tasks: [
        "Submit expedited food handling permit application",
        "Confirm kitchen booking for days 3-10",
        "Finalize ingredient budget and vendor list",
      ],
      owner: "Blueprint + Shield",
      estimated_effort: "2 days",
    },
    {
      phase: "Phase 2",
      title: "Sourcing & Preparation",
      description: "Procure ingredients, set up kitchen, design packaging.",
      tasks: [
        "Place orders with 3 local suppliers",
        "Purchase packaging and disposable serving materials",
        "Design and print marketing flyers",
        "Set up social media presence",
      ],
      owner: "Gears + Lens",
      estimated_effort: "3 days",
    },
    {
      phase: "Phase 3",
      title: "Test & Train",
      description: "Conduct dry run, train any volunteer staff, verify all systems.",
      tasks: [
        "Bake test batches of top 5 menu items",
        "Rehearse customer service flow",
        "Test POS / payment system",
        "Final health & safety walkthrough",
      ],
      owner: "Gears + Shield",
      estimated_effort: "2 days",
    },
    {
      phase: "Phase 4",
      title: "Launch & Operate",
      description: "Open for business, manage real-time operations, collect feedback.",
      tasks: [
        "Grand opening: doors open at 7am",
        "Monitor inventory levels in real-time",
        "Collect customer feedback forms",
        "Daily financial reconciliation",
      ],
      owner: "Gears + Chronicle",
      estimated_effort: "3 days",
    },
  ],
  risk_register: [
    {
      id: "risk-001",
      title: "Permit processing delay",
      severity: "critical",
      likelihood: "possible",
      impact: "Could delay launch beyond 10-day window",
      mitigation: "Expedited processing + farmers market fallback plan",
      owner: "Shield",
    },
    {
      id: "risk-002",
      title: "Budget overrun on ingredients",
      severity: "medium",
      likelihood: "likely",
      impact: "Could exceed $3,000 budget cap by 15-20%",
      mitigation: "Pre-negotiate fixed pricing with 2 suppliers, reduce menu to 5 items",
      owner: "Lens",
    },
    {
      id: "risk-003",
      title: "Kitchen equipment failure",
      severity: "high",
      likelihood: "unlikely",
      impact: "Complete production stoppage",
      mitigation: "Identify backup kitchen within 2-mile radius, test all equipment day 3",
      owner: "Gears",
    },
    {
      id: "risk-004",
      title: "Low customer turnout",
      severity: "medium",
      likelihood: "possible",
      impact: "Revenue falls short of break-even point",
      mitigation: "Social media campaign + neighborhood flyer distribution + opening day discount",
      owner: "Chronicle",
    },
  ],
  human_review_checkpoints: [
    {
      id: "review-001",
      title: "Permit application review",
      reason: "Legal document requires human signature and verification",
      phase: "Phase 1",
      required: true,
    },
    {
      id: "review-002",
      title: "Marketing material approval",
      reason: "Brand messaging and legal disclaimers need human sign-off",
      phase: "Phase 2",
      required: true,
    },
    {
      id: "review-003",
      title: "Menu pricing review",
      reason: "Final pricing strategy should reflect local market conditions",
      phase: "Phase 2",
      required: false,
    },
    {
      id: "review-004",
      title: "Health inspection readiness",
      reason: "Pre-opening safety checklist verification",
      phase: "Phase 3",
      required: true,
    },
  ],
  assumptions: [
    "The borrowed kitchen meets health code requirements for commercial food preparation",
    "Expedited permit processing is available in the target jurisdiction",
    "At least 2 reliable local ingredient suppliers can deliver within 48 hours",
    "Social media reach in the target neighborhood is sufficient for awareness",
    "Weather conditions during the 3-day opening window will permit outdoor signage",
    "No competing pop-up events are scheduled in the same neighborhood",
  ],
  alternatives: [
    {
      id: "alt-001",
      title: "Farmers Market Pivot",
      description:
        "Skip the standalone pop-up entirely and operate from a farmers market stall. Lower overhead, no kitchen permit needed, built-in foot traffic.",
      trade_offs:
        "Lower risk and cost, but reduced menu options, less brand identity, and dependent on market schedule.",
      confidence: 0.82,
    },
    {
      id: "alt-002",
      title: "Ghost Kitchen + Delivery Only",
      description:
        "Use the borrowed kitchen as a ghost kitchen. Partner with a local delivery app. No storefront needed.",
      trade_offs:
        "Eliminates foot traffic risk but adds delivery logistics complexity and app commission fees (15-30%).",
      confidence: 0.67,
    },
    {
      id: "alt-003",
      title: "Catering-First Approach",
      description:
        "Instead of a retail pop-up, pre-sell catering packages to local offices and events for the 3-day window.",
      trade_offs:
        "Guaranteed revenue if orders are secured, but requires sales effort upfront and limits community exposure.",
      confidence: 0.54,
    },
  ],
  suggested_metrics: [
    {
      name: "Daily Revenue",
      description: "Total sales revenue per operating day",
      target: "$400+ per day",
      measurement: "POS system daily totals",
    },
    {
      name: "Customer Satisfaction",
      description: "Average rating from feedback forms",
      target: "4.2+ out of 5",
      measurement: "Paper feedback forms + Google reviews",
    },
    {
      name: "Food Waste Ratio",
      description: "Percentage of prepared food unsold at end of day",
      target: "Below 15%",
      measurement: "Daily inventory count vs. production log",
    },
    {
      name: "Permit Compliance",
      description: "All required permits obtained before opening",
      target: "100% compliance",
      measurement: "Permit checklist sign-off",
    },
  ],
  confidence_notes: [
    "High confidence in kitchen sourcing — owner has verbally confirmed availability",
    "Medium confidence in permit timeline — depends on local government processing speed",
    "Low confidence in customer turnout projections — no historical data for this neighborhood",
    "High confidence in supply chain — two of three vendors have worked with the kitchen owner before",
  ],
};
