/**
 * Curated showcase data for the example simulation.
 * This represents what a real completed orchestration looks like —
 * high-quality, realistic AI-generated content for investor demos.
 */

import type {
  Run,
  Agent,
  Task,
  RunEvent,
  Outcome,
} from "@/types/entities";

// ─── Showcase Run: Data Center Outage Response ───

export const showcaseRun: Run = {
  id: "example",
  scenario_id: "showcase-dc-outage",
  status: "completed",
  mode: "explore",
  agent_roster: [
    { id: "sa-architect", name: "Strategos", role: "architect" },
    { id: "sa-analyst", name: "Prism", role: "analyst" },
    { id: "sa-operator", name: "Dispatch", role: "operator" },
    { id: "sa-guardian", name: "Sentinel", role: "guardian" },
    { id: "sa-escalation", name: "Arbiter", role: "escalation_lead" },
    { id: "sa-narrator", name: "Chronicle", role: "narrator" },
  ],
  task_graph: [
    { from_task_id: "st-001", to_task_id: "st-002", relation: "depends_on" },
    { from_task_id: "st-001", to_task_id: "st-003", relation: "depends_on" },
    { from_task_id: "st-002", to_task_id: "st-004", relation: "depends_on" },
    { from_task_id: "st-003", to_task_id: "st-005", relation: "depends_on" },
    { from_task_id: "st-004", to_task_id: "st-006", relation: "depends_on" },
    { from_task_id: "st-005", to_task_id: "st-006", relation: "depends_on" },
    { from_task_id: "st-006", to_task_id: "st-007", relation: "depends_on" },
    { from_task_id: "st-007", to_task_id: "st-008", relation: "depends_on" },
    { from_task_id: "st-007", to_task_id: "st-009", relation: "depends_on" },
    { from_task_id: "st-008", to_task_id: "st-010", relation: "depends_on" },
    { from_task_id: "st-009", to_task_id: "st-010", relation: "depends_on" },
  ],
  summary: "Data center outage — 10,000 customers affected, SLA in breach",
  started_at: "2026-04-09T15:00:00Z",
  ended_at: "2026-04-09T15:18:42Z",
  progress: 100,
};

// ─── Showcase Agents ───

export const showcaseAgents: Agent[] = [
  {
    id: "sa-architect",
    run_id: "example",
    name: "Strategos",
    role: "architect",
    capabilities: ["incident_decomposition", "dependency_mapping", "recovery_planning", "rollback_design"],
    confidence: 0.92,
    state: "done",
    current_task_id: null,
    last_action: "Finalized 4-phase recovery plan with rollback checkpoints",
    messages_sent: 18,
    messages_received: 14,
  },
  {
    id: "sa-analyst",
    run_id: "example",
    name: "Prism",
    role: "analyst",
    capabilities: ["blast_radius_analysis", "sla_calculation", "cost_modeling", "risk_scoring"],
    confidence: 0.88,
    state: "done",
    current_task_id: null,
    last_action: "SLA breach window: 3h 47m. Estimated penalty: $142K",
    messages_sent: 15,
    messages_received: 12,
  },
  {
    id: "sa-operator",
    run_id: "example",
    name: "Dispatch",
    role: "operator",
    capabilities: ["dns_failover", "load_balancer_config", "database_replication", "runbook_execution"],
    confidence: 0.94,
    state: "done",
    current_task_id: null,
    last_action: "DR region active, 97.2% of traffic rerouted successfully",
    messages_sent: 22,
    messages_received: 16,
  },
  {
    id: "sa-guardian",
    run_id: "example",
    name: "Sentinel",
    role: "guardian",
    capabilities: ["data_integrity_check", "security_audit", "compliance_verification", "change_approval"],
    confidence: 0.79,
    state: "done",
    current_task_id: null,
    last_action: "Data integrity verified: 0 records lost, 23 stale cache entries purged",
    messages_sent: 11,
    messages_received: 19,
  },
  {
    id: "sa-escalation",
    run_id: "example",
    name: "Arbiter",
    role: "escalation_lead",
    capabilities: ["stakeholder_comms", "decision_framework", "priority_triage", "vendor_escalation"],
    confidence: 0.85,
    state: "done",
    current_task_id: null,
    last_action: "Customer comms sent: 3 waves (acknowledgment, ETA, resolution)",
    messages_sent: 9,
    messages_received: 13,
  },
  {
    id: "sa-narrator",
    run_id: "example",
    name: "Chronicle",
    role: "narrator",
    capabilities: ["incident_timeline", "executive_briefing", "post_mortem_draft", "status_broadcasting"],
    confidence: 0.96,
    state: "done",
    current_task_id: null,
    last_action: "Post-incident report drafted with 7 action items",
    messages_sent: 8,
    messages_received: 24,
  },
];

// ─── Showcase Tasks ───

export const showcaseTasks: Task[] = [
  {
    id: "st-001",
    run_id: "example",
    title: "Incident triage & blast radius assessment",
    description: "Determine which services, regions, and customer segments are affected. Map dependencies. Establish severity level.",
    status: "completed",
    owner_agent_id: "sa-architect",
    depends_on: [],
    risk_level: "critical",
    phase: "Triage",
    confidence: 0.95,
    started_at: "2026-04-09T15:00:15Z",
    completed_at: "2026-04-09T15:02:30Z",
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "st-002",
    run_id: "example",
    title: "Activate disaster recovery region",
    description: "Spin up standby infrastructure in us-west2. Verify database replicas are current. Warm up application caches.",
    status: "completed",
    owner_agent_id: "sa-operator",
    depends_on: ["st-001"],
    risk_level: "high",
    phase: "Recovery",
    confidence: 0.91,
    started_at: "2026-04-09T15:02:35Z",
    completed_at: "2026-04-09T15:06:10Z",
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "st-003",
    run_id: "example",
    title: "Customer communication — wave 1 (acknowledgment)",
    description: "Send incident acknowledgment to all 10,000 affected customers via email and status page. Include estimated resolution window.",
    status: "completed",
    owner_agent_id: "sa-escalation",
    depends_on: ["st-001"],
    risk_level: "medium",
    phase: "Communication",
    confidence: 0.93,
    started_at: "2026-04-09T15:02:40Z",
    completed_at: "2026-04-09T15:04:15Z",
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "st-004",
    run_id: "example",
    title: "DNS failover & traffic rerouting",
    description: "Update DNS records to point to DR region. Configure load balancer health checks. Implement gradual traffic shift (10% → 50% → 100%).",
    status: "completed",
    owner_agent_id: "sa-operator",
    depends_on: ["st-002"],
    risk_level: "critical",
    phase: "Recovery",
    confidence: 0.87,
    started_at: "2026-04-09T15:06:15Z",
    completed_at: "2026-04-09T15:09:45Z",
    retry_count: 1,
    failure_reason: "Initial 10% shift showed elevated 5xx — paused, investigated stale TLS cert, resolved, resumed",
  },
  {
    id: "st-005",
    run_id: "example",
    title: "SLA impact analysis & financial exposure",
    description: "Calculate cumulative downtime against SLA thresholds. Model financial exposure per customer tier. Prepare credit/refund scenarios.",
    status: "completed",
    owner_agent_id: "sa-analyst",
    depends_on: ["st-003"],
    risk_level: "medium",
    phase: "Analysis",
    confidence: 0.89,
    started_at: "2026-04-09T15:04:20Z",
    completed_at: "2026-04-09T15:07:30Z",
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "st-006",
    run_id: "example",
    title: "Data integrity verification",
    description: "Run checksums against primary and replica databases. Verify transaction log continuity. Identify any data loss window.",
    status: "completed",
    owner_agent_id: "sa-guardian",
    depends_on: ["st-004", "st-005"],
    risk_level: "critical",
    phase: "Verification",
    confidence: 0.82,
    started_at: "2026-04-09T15:09:50Z",
    completed_at: "2026-04-09T15:12:20Z",
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "st-007",
    run_id: "example",
    title: "Service restoration & smoke testing",
    description: "Verify all API endpoints responding. Run synthetic transactions across critical paths. Confirm webhook deliveries resuming.",
    status: "completed",
    owner_agent_id: "sa-operator",
    depends_on: ["st-006"],
    risk_level: "high",
    phase: "Restoration",
    confidence: 0.93,
    started_at: "2026-04-09T15:12:25Z",
    completed_at: "2026-04-09T15:14:50Z",
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "st-008",
    run_id: "example",
    title: "Customer communication — wave 3 (resolution)",
    description: "Send resolution notice with summary of impact, actions taken, and any credits applied. Update status page to 'Resolved'.",
    status: "completed",
    owner_agent_id: "sa-escalation",
    depends_on: ["st-007"],
    risk_level: "low",
    phase: "Communication",
    confidence: 0.97,
    started_at: "2026-04-09T15:14:55Z",
    completed_at: "2026-04-09T15:16:10Z",
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "st-009",
    run_id: "example",
    title: "Post-incident report & action items",
    description: "Draft post-mortem: timeline, root cause, contributing factors, remediation actions. Assign owners and deadlines for each action item.",
    status: "completed",
    owner_agent_id: "sa-narrator",
    depends_on: ["st-007"],
    risk_level: "low",
    phase: "Review",
    confidence: 0.96,
    started_at: "2026-04-09T15:15:00Z",
    completed_at: "2026-04-09T15:17:45Z",
    retry_count: 0,
    failure_reason: null,
  },
  {
    id: "st-010",
    run_id: "example",
    title: "Resilience hardening plan",
    description: "Design improvements to prevent recurrence: multi-region active-active, automated failover testing, enhanced monitoring. Estimate cost and timeline.",
    status: "completed",
    owner_agent_id: "sa-architect",
    depends_on: ["st-008", "st-009"],
    risk_level: "medium",
    phase: "Hardening",
    confidence: 0.91,
    started_at: "2026-04-09T15:17:50Z",
    completed_at: "2026-04-09T15:18:40Z",
    retry_count: 0,
    failure_reason: null,
  },
];

// ─── Showcase Events ───

export const showcaseEvents: RunEvent[] = [
  { id: "se-001", run_id: "example", type: "run_started", actor: "system", payload: { mode: "explore", scenario: "Data Center Outage Response" }, timestamp: "2026-04-09T15:00:00Z", sequence: 1 },
  { id: "se-002", run_id: "example", type: "scenario_compiled", actor: "system", payload: { domain: "infrastructure", safety_status: "safe", agents_count: 6, tasks_count: 10 }, timestamp: "2026-04-09T15:00:12Z", sequence: 2 },
  { id: "se-003", run_id: "example", type: "agent_spawned", actor: "Strategos", payload: { role: "architect" }, timestamp: "2026-04-09T15:00:13Z", sequence: 3 },
  { id: "se-004", run_id: "example", type: "agent_spawned", actor: "Prism", payload: { role: "analyst" }, timestamp: "2026-04-09T15:00:13Z", sequence: 4 },
  { id: "se-005", run_id: "example", type: "agent_spawned", actor: "Dispatch", payload: { role: "operator" }, timestamp: "2026-04-09T15:00:14Z", sequence: 5 },
  { id: "se-006", run_id: "example", type: "agent_spawned", actor: "Sentinel", payload: { role: "guardian" }, timestamp: "2026-04-09T15:00:14Z", sequence: 6 },
  { id: "se-007", run_id: "example", type: "agent_spawned", actor: "Arbiter", payload: { role: "escalation_lead" }, timestamp: "2026-04-09T15:00:14Z", sequence: 7 },
  { id: "se-008", run_id: "example", type: "agent_spawned", actor: "Chronicle", payload: { role: "narrator" }, timestamp: "2026-04-09T15:00:15Z", sequence: 8 },
  { id: "se-009", run_id: "example", type: "agent_thinking", actor: "Strategos", payload: { thought: "Primary region us-east1 is offline. Mapping blast radius: 10,247 customer accounts, 34 microservices, 3 dependent SaaS integrations." }, timestamp: "2026-04-09T15:00:20Z", sequence: 9 },
  { id: "se-010", run_id: "example", type: "task_created", actor: "Strategos", payload: { task_id: "st-001", title: "Incident triage & blast radius assessment" }, timestamp: "2026-04-09T15:00:25Z", sequence: 10 },
  { id: "se-011", run_id: "example", type: "task_status_changed", actor: "Strategos", payload: { task_id: "st-001", from: "queued", to: "active" }, timestamp: "2026-04-09T15:00:30Z", sequence: 11 },
  { id: "se-012", run_id: "example", type: "risk_identified", actor: "Sentinel", payload: { risk: "Database replication lag detected: 47 seconds behind primary. Risk of data loss if failover proceeds without verification.", severity: "critical" }, timestamp: "2026-04-09T15:01:15Z", sequence: 12 },
  { id: "se-013", run_id: "example", type: "agent_action", actor: "Strategos", payload: { action: "Blast radius confirmed: 10,247 accounts across 3 customer tiers (Enterprise: 127, Business: 2,340, Starter: 7,780). All 34 services in us-east1 impacted." }, timestamp: "2026-04-09T15:02:25Z", sequence: 13 },
  { id: "se-014", run_id: "example", type: "task_status_changed", actor: "Strategos", payload: { task_id: "st-001", from: "active", to: "completed" }, timestamp: "2026-04-09T15:02:30Z", sequence: 14 },
  { id: "se-015", run_id: "example", type: "task_assigned", actor: "system", payload: { task_id: "st-002", agent: "Dispatch", role: "operator" }, timestamp: "2026-04-09T15:02:35Z", sequence: 15 },
  { id: "se-016", run_id: "example", type: "task_assigned", actor: "system", payload: { task_id: "st-003", agent: "Arbiter", role: "escalation_lead" }, timestamp: "2026-04-09T15:02:40Z", sequence: 16 },
  { id: "se-017", run_id: "example", type: "agent_thinking", actor: "Dispatch", payload: { thought: "DR region us-west2 has warm standby. Checking: replica freshness, certificate validity, DNS TTL..." }, timestamp: "2026-04-09T15:03:00Z", sequence: 17 },
  { id: "se-018", run_id: "example", type: "agent_message", actor: "Arbiter", payload: { to: "Prism", message: "Need SLA breach calculation for the customer comms. Enterprise tier has 4-hour RTO — we're at T+45m." }, timestamp: "2026-04-09T15:03:30Z", sequence: 18 },
  { id: "se-019", run_id: "example", type: "agent_action", actor: "Arbiter", payload: { action: "Customer acknowledgment sent to 10,247 accounts. Status page updated to 'Investigating'. ETA: 2 hours." }, timestamp: "2026-04-09T15:04:10Z", sequence: 19 },
  { id: "se-020", run_id: "example", type: "agent_thinking", actor: "Prism", payload: { thought: "Enterprise SLA: 99.99% = 4.32 min/month. Current breach: 45 min. Financial exposure: $142K in credits across 127 Enterprise accounts." }, timestamp: "2026-04-09T15:05:00Z", sequence: 20 },
  { id: "se-021", run_id: "example", type: "agent_action", actor: "Dispatch", payload: { action: "DR region activated. Database replica verified: 47s lag resolved, now at 0s. Beginning traffic shift: 10% canary." }, timestamp: "2026-04-09T15:06:05Z", sequence: 21 },
  { id: "se-022", run_id: "example", type: "risk_identified", actor: "Sentinel", payload: { risk: "TLS certificate in DR region expired 3 days ago — not caught by monitoring. Canary traffic showing elevated 5xx.", severity: "high" }, timestamp: "2026-04-09T15:07:00Z", sequence: 22 },
  { id: "se-023", run_id: "example", type: "retry_triggered", actor: "system", payload: { task_id: "st-004", attempt: 2, reason: "Stale TLS certificate in DR region causing 5xx on canary traffic. Renewing cert before resuming." }, timestamp: "2026-04-09T15:07:15Z", sequence: 23 },
  { id: "se-024", run_id: "example", type: "decision_gate_created", actor: "Sentinel", payload: { gate_id: "sg-001", reason: "TLS cert expired in DR region. Renewing now, but this reveals a monitoring gap. Proceed with failover after renewal, or investigate further?", risk_level: "high" }, timestamp: "2026-04-09T15:07:20Z", sequence: 24 },
  { id: "se-025", run_id: "example", type: "decision_gate_resolved", actor: "system", payload: { gate_id: "sg-001", action: "Proceed after cert renewal — investigation deferred to post-incident" }, timestamp: "2026-04-09T15:07:45Z", sequence: 25 },
  { id: "se-026", run_id: "example", type: "agent_action", actor: "Dispatch", payload: { action: "TLS cert renewed. Resuming traffic shift: 10% → 50% → 100%. All health checks green." }, timestamp: "2026-04-09T15:08:30Z", sequence: 26 },
  { id: "se-027", run_id: "example", type: "narrator_update", actor: "Chronicle", payload: { summary: "Recovery entering critical phase. DR region is now handling 50% of traffic with clean health checks. A stale TLS certificate caused a brief setback but was resolved in under 2 minutes. SLA breach stands at 1h 8m for Enterprise tier." }, timestamp: "2026-04-09T15:09:00Z", sequence: 27 },
  { id: "se-028", run_id: "example", type: "task_status_changed", actor: "Dispatch", payload: { task_id: "st-004", from: "active", to: "completed" }, timestamp: "2026-04-09T15:09:45Z", sequence: 28 },
  { id: "se-029", run_id: "example", type: "agent_action", actor: "Sentinel", payload: { action: "Data integrity check complete. Checksums match across primary and replica. 0 records lost. 23 stale cache entries purged." }, timestamp: "2026-04-09T15:12:15Z", sequence: 29 },
  { id: "se-030", run_id: "example", type: "agent_action", actor: "Dispatch", payload: { action: "All 34 services responding. Synthetic transactions passing. Webhook backlog draining (2,847 queued → processing at 120/sec)." }, timestamp: "2026-04-09T15:14:45Z", sequence: 30 },
  { id: "se-031", run_id: "example", type: "agent_action", actor: "Arbiter", payload: { action: "Resolution notice sent. Enterprise accounts receiving automatic 15% credit. Status page: Resolved." }, timestamp: "2026-04-09T15:16:05Z", sequence: 31 },
  { id: "se-032", run_id: "example", type: "narrator_update", actor: "Chronicle", payload: { summary: "Incident resolved in 18 minutes. All services restored to DR region. Zero data loss confirmed. Post-mortem identifies 7 action items including automated cert rotation, multi-region active-active architecture, and enhanced DR testing cadence." }, timestamp: "2026-04-09T15:17:40Z", sequence: 32 },
  { id: "se-033", run_id: "example", type: "run_completed", actor: "system", payload: { duration_minutes: 18, tasks_completed: 10, agents_involved: 6 }, timestamp: "2026-04-09T15:18:42Z", sequence: 33 },
];

// ─── Showcase Outcome ───

export const showcaseOutcome: Outcome = {
  id: "outcome-dc-outage",
  run_id: "example",
  executive_summary:
    "Incident resolved in 18 minutes with zero data loss. All 10,247 affected customer accounts restored via DR failover to us-west2. A stale TLS certificate in the DR region caused a 90-second setback during traffic migration but was identified and resolved by the Guardian agent. Enterprise SLA breach totaled 1h 18m, triggering automatic 15% credits ($142K exposure). Post-incident analysis identified 7 hardening actions to prevent recurrence.",
  operating_plan: [
    {
      phase: "Phase 1",
      title: "Triage & Assessment",
      description: "Rapid blast radius mapping and severity classification within the first 2 minutes.",
      tasks: [
        "Map all affected services, regions, and customer segments",
        "Classify incident severity (SEV-1: full region outage)",
        "Identify database replication lag and quantify data loss risk",
        "Establish communication cadence: updates every 15 minutes",
      ],
      owner: "Strategos (Architect)",
      estimated_effort: "2 minutes",
    },
    {
      phase: "Phase 2",
      title: "DR Activation & Failover",
      description: "Activate disaster recovery infrastructure and migrate traffic with staged canary deployment.",
      tasks: [
        "Verify DR region readiness (database replicas, cache warmth, certificates)",
        "Initiate gradual traffic shift: 10% canary → 50% → 100%",
        "Monitor error rates and latency at each stage",
        "Resolve TLS certificate expiration discovered during canary",
      ],
      owner: "Dispatch (Operator)",
      estimated_effort: "7 minutes",
    },
    {
      phase: "Phase 3",
      title: "Verification & Communication",
      description: "Validate data integrity, restore full service, and communicate resolution to all stakeholders.",
      tasks: [
        "Run database checksum verification across all tables",
        "Execute synthetic transaction tests on all critical API paths",
        "Send 3-wave customer communication (acknowledge → update → resolve)",
        "Update status page and clear incident banner",
      ],
      owner: "Sentinel (Guardian) + Arbiter (Escalation)",
      estimated_effort: "6 minutes",
    },
    {
      phase: "Phase 4",
      title: "Post-Incident Hardening",
      description: "Document learnings and design improvements to prevent recurrence.",
      tasks: [
        "Draft post-mortem with root cause analysis",
        "Identify 7 remediation action items with owners and deadlines",
        "Design multi-region active-active architecture proposal",
        "Schedule quarterly DR failover testing",
      ],
      owner: "Chronicle (Narrator) + Strategos (Architect)",
      estimated_effort: "3 minutes",
    },
  ],
  risk_register: [
    {
      id: "sr-001",
      title: "Database replication lag",
      severity: "critical",
      likelihood: "likely",
      impact: "Data loss of up to 47 seconds of transactions during failover window",
      mitigation: "Verified replication caught up to 0s lag before initiating failover. Zero data loss confirmed.",
      owner: "Sentinel",
    },
    {
      id: "sr-002",
      title: "Expired TLS certificate in DR region",
      severity: "high",
      likelihood: "certain",
      impact: "Elevated 5xx errors during initial canary traffic shift, delaying recovery by ~90 seconds",
      mitigation: "Certificate renewed in-place. Action item: implement automated cert rotation and pre-failover validation.",
      owner: "Dispatch",
    },
    {
      id: "sr-003",
      title: "Enterprise SLA breach financial exposure",
      severity: "high",
      likelihood: "certain",
      impact: "$142K in automatic credits across 127 Enterprise accounts (15% monthly credit per SLA terms)",
      mitigation: "Credits processed automatically. Account management team notified for relationship follow-up.",
      owner: "Arbiter",
    },
    {
      id: "sr-004",
      title: "Webhook delivery backlog",
      severity: "medium",
      likelihood: "certain",
      impact: "2,847 webhooks queued during outage, partner integrations temporarily stale",
      mitigation: "Backlog drained at 120/sec post-recovery. All deliveries confirmed within 25 minutes of resolution.",
      owner: "Dispatch",
    },
  ],
  human_review_checkpoints: [
    {
      id: "sr-cp-001",
      title: "Proceed with failover despite TLS issue",
      reason: "Expired cert in DR region revealed monitoring gap. Decision: renew and proceed vs. investigate further first.",
      phase: "Phase 2",
      required: true,
    },
    {
      id: "sr-cp-002",
      title: "Approve customer credit calculation",
      reason: "Enterprise SLA breach triggers automatic 15% credit. Review calculation methodology before batch processing.",
      phase: "Phase 3",
      required: true,
    },
    {
      id: "sr-cp-003",
      title: "Validate post-mortem action items",
      reason: "7 proposed action items require resource allocation and priority assignment from engineering leadership.",
      phase: "Phase 4",
      required: false,
    },
  ],
  assumptions: [
    "DR region us-west2 has sufficient capacity to handle 100% of production traffic",
    "Database replication is synchronous enough that sub-minute lag is acceptable for failover",
    "Customer SLA terms specify automatic credit calculation based on measured downtime",
    "Status page is the primary channel for real-time incident communication",
    "Webhook consumers implement idempotency and can handle delayed/duplicate deliveries",
    "Engineering team has access to renew TLS certificates without a change approval process during incidents",
  ],
  alternatives: [
    {
      id: "sa-001",
      title: "Wait for primary region recovery",
      description: "Instead of failing over to DR, wait for the cloud provider to restore us-east1. Avoids failover complexity and certificate issues.",
      trade_offs: "Zero failover risk, but unpredictable timeline. Cloud provider estimated 2-4 hours. Enterprise SLA breach would reach $380K+ in credits.",
      confidence: 0.3,
    },
    {
      id: "sa-002",
      title: "Partial failover (Enterprise only)",
      description: "Fail over only Enterprise tier accounts to DR region, leaving Business and Starter on degraded primary. Limits blast radius of failover issues.",
      trade_offs: "Reduces failover complexity and risk but creates operational split-brain. Business/Starter customers see extended outage. Reputational risk.",
      confidence: 0.55,
    },
    {
      id: "sa-003",
      title: "Multi-region active-active (future state)",
      description: "Implement active-active across 3 regions so no failover is needed — traffic automatically routes around failures.",
      trade_offs: "Eliminates single-region dependency entirely. Requires 6-month engineering investment (~$400K) and ongoing 2.3x infrastructure cost increase.",
      confidence: 0.92,
    },
  ],
  suggested_metrics: [
    { name: "Time to Detect", description: "Time from failure to alert firing", target: "< 2 minutes", measurement: "Monitoring system timestamp delta" },
    { name: "Time to Recover", description: "Time from detection to full service restoration", target: "< 30 minutes", measurement: "Status page resolved timestamp - alert timestamp" },
    { name: "Data Loss", description: "Records lost during failover window", target: "0 records", measurement: "Primary-replica checksum comparison" },
    { name: "Customer Impact", description: "Number of affected customers and SLA breach duration", target: "< 1 hour breach", measurement: "Uptime monitoring + SLA calculation engine" },
  ],
  confidence_notes: [
    "High confidence in DR failover — us-west2 was provisioned and warm, failover completed in 7 minutes",
    "High confidence in data integrity — checksums verified, zero records lost across all tables",
    "Medium confidence in SLA calculation — credit amounts are estimates pending final reconciliation with billing system",
    "Low confidence in prevention timeline — multi-region active-active requires significant engineering investment with uncertain delivery date",
  ],
};

// ─── Landing Page Showcase Cards ───

export const SHOWCASE_CARDS = [
  {
    title: "Data Center Outage",
    domain: "Infrastructure",
    agents: 6,
    tasks: 10,
    duration: "18 min",
    result: "Zero data loss, 10K customers restored",
    color: "#ef4444",
  },
  {
    title: "Product Launch Sprint",
    domain: "Go-to-Market",
    agents: 5,
    tasks: 14,
    duration: "12 min",
    result: "$50K budget allocated across 4 channels",
    color: "#6366f1",
  },
  {
    title: "Supply Chain Recovery",
    domain: "Logistics",
    agents: 6,
    tasks: 11,
    duration: "15 min",
    result: "3 backup suppliers secured, 200 orders triaged",
    color: "#f59e0b",
  },
];
