import type { ScenarioTemplate } from "@/types/entities";

export const BUILT_IN_TEMPLATES: ScenarioTemplate[] = [
  {
    id: "tmpl-bakery-sprint",
    title: "Pop-Up Bakery Sprint",
    teaser: "10 days. No kitchen. One chance to impress the neighborhood.",
    prompt: "Launch a pop-up bakery in 10 days with a borrowed kitchen, limited budget, and no prior food business experience.",
    domain: "operations",
    difficulty: "medium",
    safety_classification: "safe",
    constraints: { urgency: "high", risk_tolerance: "balanced", autonomy: "guided" },
    suggested_agent_roster: ["architect", "analyst", "operator", "guardian", "narrator"],
    suggested_mode: "play",
    category: "operations_rescue",
  },
  {
    id: "tmpl-shipping-breakdown",
    title: "Shipping Breakdown Recovery",
    teaser: "Half your fleet is grounded. Customers are waiting.",
    prompt: "Recover from a fictional shipping company breakdown where 60% of delivery trucks are offline due to a software glitch, with 2,000 packages undelivered.",
    domain: "logistics",
    difficulty: "hard",
    safety_classification: "safe",
    constraints: { urgency: "critical", risk_tolerance: "conservative", autonomy: "supervised" },
    suggested_agent_roster: ["architect", "analyst", "operator", "guardian", "escalation_lead", "narrator"],
    suggested_mode: "prove",
    category: "supply_chain",
  },
  {
    id: "tmpl-robot-parade",
    title: "Weekend Robot Parade",
    teaser: "Volunteers are scarce. Robots are unpredictable. The mayor is watching.",
    prompt: "Plan a weekend robot parade through downtown with 15 amateur robots, limited volunteers, uncertain weather, and a live audience of 500.",
    domain: "events",
    difficulty: "medium",
    safety_classification: "safe",
    constraints: { urgency: "medium", risk_tolerance: "balanced", autonomy: "guided" },
    suggested_agent_roster: ["architect", "operator", "guardian", "narrator"],
    suggested_mode: "play",
    category: "event_planning",
  },
  {
    id: "tmpl-museum-audio-fail",
    title: "Museum Without Audio",
    teaser: "The audio guide system just died. 200 visitors are already inside.",
    prompt: "Run a museum for the rest of the day after the entire audio guide system fails unexpectedly, with 200 visitors already inside and a school group arriving in an hour.",
    domain: "operations",
    difficulty: "medium",
    safety_classification: "safe",
    constraints: { urgency: "high", risk_tolerance: "balanced", autonomy: "guided" },
    suggested_agent_roster: ["architect", "analyst", "operator", "narrator"],
    suggested_mode: "explore",
    category: "operations_rescue",
  },
  {
    id: "tmpl-umbrella-pilot",
    title: "Citywide Umbrella Sharing",
    teaser: "Rain is forecast all week. Can a sharing economy work for umbrellas?",
    prompt: "Organize a citywide umbrella-sharing pilot during a rainy week with 500 umbrellas, 20 distribution points, and no existing logistics network.",
    domain: "civic",
    difficulty: "hard",
    safety_classification: "safe",
    constraints: { urgency: "medium", risk_tolerance: "balanced", autonomy: "autonomous" },
    suggested_agent_roster: ["architect", "analyst", "operator", "guardian", "narrator"],
    suggested_mode: "explore",
    category: "public_service",
  },
  {
    id: "tmpl-snack-mixup",
    title: "Snack Factory Packaging Mixup",
    teaser: "Every bag has the wrong label. Shipments leave in 6 hours.",
    prompt: "Recover from a fictional snack factory packaging mix-up where 10,000 bags have incorrect labels, shipments are scheduled in 6 hours, and the labeling machine is jammed.",
    domain: "manufacturing",
    difficulty: "hard",
    safety_classification: "safe",
    constraints: { urgency: "critical", risk_tolerance: "conservative", autonomy: "supervised" },
    suggested_agent_roster: ["architect", "analyst", "operator", "guardian", "escalation_lead", "narrator"],
    suggested_mode: "prove",
    category: "supply_chain",
  },
  {
    id: "tmpl-support-tsunami",
    title: "Support Ticket Tsunami",
    teaser: "3,000 tickets. 5 agents. One very broken feature.",
    prompt: "Triage and respond to a sudden wave of 3,000 support tickets caused by a broken billing feature, with only 5 support agents available and angry customers on social media.",
    domain: "support",
    difficulty: "hard",
    safety_classification: "safe",
    constraints: { urgency: "critical", risk_tolerance: "balanced", autonomy: "guided" },
    suggested_agent_roster: ["architect", "analyst", "operator", "escalation_lead", "narrator"],
    suggested_mode: "prove",
    category: "support_triage",
  },
  {
    id: "tmpl-cat-cafe-opening",
    title: "Cat Café Grand Opening",
    teaser: "12 cats. 1 health inspector. A line around the block.",
    prompt: "Open a cat café tomorrow with 12 adopted cats, a health inspection at 9am, a social media influencer arriving at noon, and a line of 100 customers already forming.",
    domain: "hospitality",
    difficulty: "easy",
    safety_classification: "safe",
    constraints: { urgency: "high", risk_tolerance: "balanced", autonomy: "autonomous" },
    suggested_agent_roster: ["architect", "operator", "guardian", "narrator"],
    suggested_mode: "play",
    category: "operations_rescue",
  },
  {
    id: "tmpl-impossible-move",
    title: "Move an Entire Office Overnight",
    teaser: "One night. 200 desks. The CEO wants everyone productive by 9am.",
    prompt: "Relocate a 200-person office to a new building overnight so that every employee can sit down and work normally by 9am the next morning, with no advance notice to staff.",
    domain: "operations",
    difficulty: "impossible",
    safety_classification: "safe",
    constraints: { urgency: "critical", risk_tolerance: "aggressive", autonomy: "autonomous" },
    suggested_agent_roster: ["architect", "analyst", "operator", "guardian", "escalation_lead", "narrator"],
    suggested_mode: "explore",
    category: "absurd_challenge",
  },
  {
    id: "tmpl-festival-rain",
    title: "Festival Downpour Pivot",
    teaser: "The forecast just changed. 5,000 attendees. All stages are outdoors.",
    prompt: "Pivot an outdoor music festival to handle a sudden severe rain forecast 4 hours before gates open, with 5,000 ticket holders, 8 outdoor stages, and no indoor backup venue.",
    domain: "events",
    difficulty: "hard",
    safety_classification: "safe",
    constraints: { urgency: "critical", risk_tolerance: "conservative", autonomy: "supervised" },
    suggested_agent_roster: ["architect", "analyst", "operator", "guardian", "escalation_lead", "narrator"],
    suggested_mode: "prove",
    category: "event_planning",
  },
];

export function getRandomTemplate(): ScenarioTemplate {
  return BUILT_IN_TEMPLATES[Math.floor(Math.random() * BUILT_IN_TEMPLATES.length)];
}
